services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "7000:7000"
      - "9229:9229"
    depends_on:
      - postgres
    restart: always


  postgres:
    container_name: postgres
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

volumes:
  postgres_db:
