services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # Web-интерфейс и S3 API
      - "9001:9001"   # Панель управления MinIO
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  postgres:
    container_name: postgres
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

#  main:
#    container_name: main
#    build:
#      context: .
#    env_file:
#      - .env
#    volumes:
#      - .:/usr/src/app
#      - /usr/src/app/node_modules
#    ports:
#      - "7000:7000"
#      - "9229:9229"
#    depends_on:
#      - postgres
#    restart: always

volumes:
  postgres_db:
  minio_data:
